title = "Miguel Côrte"

[params.author]
  name = "Miguel Côrte"
  image = "img/author.jpg"
  headline = "Technical Advisor & Automation Advocate"
  bio = "Technical Advisor & Automation Advocate helping teams turn complexity into competitive advantage. I design and implement AI-driven workflows, automated systems, and observability platforms that improve reliability, scale engineering teams, and drive strategic impact."
  links = [
    { linkedin = "https://linkedin.com/in/miguelgoncalvesc" },
    { email = "mailto:hello@mcorte.com" },
    { github = "https://github.com/miguelgoncalvesc" }
  ]
