# Main Navigation Menu

[[main]]
  name = "About"
  pageRef = "about"
  weight = 10

[[main]]
  name = "Posts"
  pageRef = "posts"
  weight = 20

[[main]]
  name = "Focus"
  pageRef = "projects"
  weight = 30

# Footer Menu

[[footer]]
  name = "Privacy"
  url = "#"
