# Blowfish Theme Parameters

# --- Global ---
colorScheme = "noir"
defaultAppearance = "dark"
autoSwitchAppearance = false
enableSearch = true
enableCodeCopy = true
enableScrollToTop = true
mainSections = ["posts"]
smartTOC = true

# --- Header ---
[header]
  layout = "fixed-fill-blur"

# --- Footer ---
[footer]
  showMenu = true
  showCopyright = true
  showThemeAttribution = true
  showAppearanceSwitcher = true
  showScrollToTop = true

# --- Homepage ---
[homepage]
  layout = "background"
  showRecent = true
  showRecentItems = 3
  showMoreLink = true
  showMoreLinkDest = "/posts"
  cardView = true
  cardViewScreenWidth = false
  layoutBackgroundBlur = true

# --- Article ---
[article]
  showDate = true
  showViews = false
  showLikes = false
  showDateOnlyInArticle = false
  showDateUpdated = true
  showAuthor = true
  showHero = true
  heroStyle = "big"
  showBreadcrumbs = true
  showDraftLabel = false
  showEdit = false
  showHeadingAnchors = true
  showPagination = true
  invertPagination = false
  showReadingTime = true
  showTableOfContents = true
  showRelatedContent = true
  relatedContentLimit = 3
  showTaxonomies = true
  showAuthorsBadges = false
  showWordCount = false
  showSummary = true

# --- List ---
[list]
  showHero = false
  heroStyle = "background"
  showBreadcrumbs = false
  showSummary = true
  showViews = false
  showLikes = false
  showTableOfContents = false
  showCards = true
  groupByYear = true
  cardView = true
  cardViewScreenWidth = false

# --- Taxonomy ---
[taxonomy]
  showTermCount = true
  showHero = false
  heroStyle = "background"
  showBreadcrumbs = false
  showViews = false
  showLikes = false
  showTableOfContents = false

# --- Term ---
[term]
  showHero = false
  heroStyle = "background"
  showBreadcrumbs = false
  showViews = false
  showLikes = false
  showTableOfContents = false
  groupByYear = false
  cardView = true
  cardViewScreenWidth = false
